# Generated by Django 5.2.17 on 2026-10-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('delta', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='variação (%)')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('online', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fonte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PontoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(unique=True, verbose_name='momento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor total')),
                ('readings_per_min', models.PositiveIntegerField(verbose_name='leituras por minuto')),
            ],
            options={
                'verbose_name': 'ponto da série',
                'verbose_name_plural': 'pontos da série',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='código')),
                ('kind', models.CharField(max_length=30, verbose_name='tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('delta', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='variação (%)')),
                ('status', models.CharField(choices=[('ok', 'Normal'), ('atencao', 'Atenção'), ('critico', 'Crítico')], max_length=10)),
                ('at', models.DateTimeField(verbose_name='momento')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='core.fonte')),
            ],
            options={
                'verbose_name_plural': 'leituras',
                'ordering': ['-at'],
            },
        ),
    ]
