# Generated by Django 5.2.17 on 2026-10-05 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dados_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('unit', models.CharField(max_length=30, verbose_name='unidade')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('price_shock', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='choque de preço (%)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='volume (12 meses)')),
                ('hedge', models.PositiveSmallIntegerField(verbose_name='proteção/hedge (%)')),
                ('baseline_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='custo base')),
                ('scenario_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='custo no cenário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cenarios', to='core.commodity')),
            ],
            options={
                'verbose_name': 'cenário',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrecoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='mês')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='mínimo previsto')),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='máximo previsto')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='é previsão')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='core.commodity')),
            ],
            options={
                'verbose_name': 'preço mensal',
                'verbose_name_plural': 'preços mensais',
                'ordering': ['commodity', 'month'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'month'), name='preco_unico_por_mes')],
            },
        ),
    ]
