# Generated by Django 5.2.17 on 2026-10-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dados_commodities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=10, verbose_name='tipo')),
                ('month', models.DateField(verbose_name='mês da decisão')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='volume')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço fechado')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisoes', to='core.commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'decisão',
                'verbose_name_plural': 'decisões',
                'ordering': ['-month', '-created_at'],
            },
        ),
    ]
