# Generated by Django 5.2.17 on 2026-10-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_decisoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='arquivo')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='criadas')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='atualizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importação de dados',
                'verbose_name_plural': 'importações de dados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço-alvo')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta',
                'constraints': [models.UniqueConstraint(fields=('user', 'commodity'), name='meta_unica')],
            },
        ),
    ]
